version: '3.7'

services:
  pgvectodotrs:
    container_name: pgvectodotrs
    image: tensorchord/pgvecto-rs:pg16-v0.3.0-alpha.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres -c max_connections=200
    shm_size: 8g
    ports:
      - 54321:5432
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8Gb
