version: '3.7'

services:
  pgvectorscale:
    container_name: pgvectorscale
    image: samarthp/pgvectorscale
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    # shared_buffers should be 25% of memory
    # maintenance_work_mem should be ~65%
    command: postgres -c max_connections=200
    # shm_size should be shared_buffers + maintenance_work_mem
    shm_size: 8g
    ports:
      - 54321:5432
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4Gb
